[package]
name = "ssh-picker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
crossterm = "0.28"
dirs = "5"
glob = "0.3"
home = "0.5"
ratatui = "0.28"
serde = { version = "1", features = ["derive"] }
ssh2-config = "0.5"
thiserror = "1"
toml = "0.8"
